version: "3.7"

services:
  raspberry_circuit:
    build: raspberry_circuit/
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1883
    depends_on:
      - mqtt_broker
    networks:
      - rasp_network

  raspberry_server:
    build: raspberry_server/
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1883
    depends_on:
      - mqtt_broker
    networks:
      - rasp_network
    ports:
      - "3001:3001"

  mqtt_broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      - rasp_network

networks:
  rasp_network:
    driver: bridge
